// Generated by CoffeeScript 1.4.0
var Proxy;

module.exports = {
  Proxy: Proxy = (function() {

    function Proxy(config) {
      console.log('init EtProxy with ', config);
    }

    Proxy.prototype.get = function(path, params, callback) {
      var error;
      console.log('Proxy.get', path, params, callback);
      error = null;
      return callback("fake data", error);
    };

    return Proxy;

  })()
};
