// Generated by CoffeeScript 1.4.0
var Proxy;

module.exports = {
  Proxy: Proxy = (function() {

    function Proxy(config) {
      console.log('init Proxy');
      this.url = config.url;
    }

    Proxy.prototype.get = function(path, callback, params) {
      console.log('Proxy.get', this.url + path, callback);
      return require('http').get(this.url + path, function(res) {
        return res.on('data', function(data) {
          return callback(data);
        });
      });
    };

    return Proxy;

  })()
};
